apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: transaction-page-deployment
spec:
  selector:
    matchLabels:
      app: transaction-page
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: transaction-page
    spec:
      containers:
        - name: transaction-page
          image: 127.0.0.1:9001/demo_repo/jenkins-demo # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: transaction-page-svc
spec:
  type: NodePort
  selector:
    app: transaction-page
  ports:
    - protocol: "TCP"
      port: 80 # The port that the service is running on in the cluster
      targetPort: 80 # The port exposed by the service
      nodePort: 30007